### ISSUE TITLE
Replay does not work with Preview Serverless (AI scaling)

### ISSUE THREAD

**Issue by cjsekl** [aws/redshift-test-drive#157]
Running Replay on a Serverless workgroup on the AI Scaling preview track fails with:

```
Traceback (most recent call last):
  File "/home/ec2-user/redshift-test-drive/common/util.py", line 93, in cluster_dict
    cluster["base_rpu"] = response["workgroup"]["baseCapacity"]
KeyError: 'baseCapacity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/redshift-test-drive/core/replay/replay.py", line 237, in <module>
    main()
  File "/home/ec2-user/redshift-test-drive/core/replay/replay.py", line 42, in main
    cluster = cluster_dict(config["target_cluster_endpoint"], is_serverless_endpoint)
  File "/home/ec2-user/redshift-test-drive/common/util.py", line 95, in cluster_dict
    if e.response["Error"]["Code"] == "ResourceNotFoundException":
AttributeError: 'KeyError' object has no attribute 'response'
```

I'm guessing because these workgroups don't have base capacity. It looks like the exception block is meant to handle it gracefully but doesn't cover this case.

Worked around it by setting `cluster["base_rpu"] = "N/A"`

**Comment by cjsekl** [comment]
Ignore me, works with later releases
